{{- $kind := "hello" -}}
{{- $app := printf "%s-%s" .Values.resource.name $kind -}}
{{- $spec := dict }}
{{- $_ := merge $spec .Values.resource.spec .Values.default -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ $app }}
  labels:
    app: {{ $app }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ $spec.size }}
  template:
    metadata:
      labels:
        app: {{ $app }}
        resource: {{ .Values.resource.name }}
    spec:
{{- if $spec.nodeSelector }}
      nodeSelector:
{{ toYaml $spec.nodeSelector | indent 8 }}
{{ end -}}
{{- if $spec.tolerations }}
      tolerations:
{{ toYaml $spec.tolerations | indent 8 }}
{{ end }}
      containers:
        - name: {{ $kind }}
{{- with $spec.image }}
          image: {{ .name }}:{{ .tag }}
          imagePullPolicy: {{ .pullPolicy }}{{ end }}
          ports:
            - containerPort: 80
{{ if $spec.resources }}
          resources:
{{ toYaml $spec.resources | indent 12 }}
{{ end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1