apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resource.name }}
  labels:
    k8s-app: {{ .Values.resource.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    k8s-app: {{ .Values.resource.name }}-httpd
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: {{ .Values.resource.spec.exposure }}
